// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxrchmsxuzwdnjxpjsoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cmNobXN4dXp3ZG5qeHBqc29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODQ2OTEsImV4cCI6MjA3MDA2MDY5MX0.JdheBStWq9tZYEb6ZBv_M_KRfzWtgY95iZCfR5t1spw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});